# [dein.toml]
[[plugins]]
repo = 'Shougo/dein.vim'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

# ファイルツリーを表示
[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['ryanoasis/vim-devicons']
hook_add='''
nnoremap <silent> <Leader>e :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'tomasr/molokai'

#[[plugins]]
#repo = 'ycm-core/YouCompleteMe'

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = "chrisbra/csv.vim"

[[plugins]]
repo = "altercation/vim-colors-solarized"

[[plugins]]
repo = "w0ng/vim-hybrid"

[[plugins]]
repo = 'lotabout/skim'

[[plugins]]
repo = 'ifreund/skim-preview.vim'

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = '''
" nnoremap <C-l> :ToggleTerm<CR>
" set
autocmd TermEnter term://*toggleterm#*
      \ tnoremap <silent><c-t> <Cmd>exe v:count1 . "ToggleTerm"<CR>

" By applying the mappings this way you can pass a count to your
" mapping to open a specific window.
" For example: 2<C-t> will open terminal 2
nnoremap <silent><c-t> <Cmd>exe v:count1 . "ToggleTerm"<CR>
inoremap <silent><c-t> <Esc><Cmd>exe v:count1 . "ToggleTerm"<CR>
'''
hook_source = '''
lua << EOF
require("toggleterm").setup({
  size = 20,
  open_mapping = [[<c-\>]],
  hide_numbers = true,
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = 2,
  start_in_insert = true,
  insert_mappings = true,
  persist_size = true,
  close_on_exit = true,
  shell = vim.o.shell,
  float_opts = {
    border = "curved",
    winblend = 0,
    highlights = {
      border = "Normal",
      background = "Normal",
    },
  },
})
EOF
'''

[[plugins]]
repo = 'jesseduffield/lazygit'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

