[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'critiqjo/lldb.nvim'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'

[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'taketwo/vim-ros'
